### ISSUE TITLE
Criar tela de login

### ISSUE THREAD

**Issue by mbagatini** [mbagatini/ProjetoCostura#1]
Será necessário criar uma tela de login para o acesso ao programa.

**Comment by lucaswantz** [comment]
Já tem uma tela de login no projeto, poderemos utilizar as classes e fazer ela WEB... Acho que esse é o primeiro passo, depois tu poderias criar um projeto do tipo JSP pra ser WEB, e ir criando as telas...

**Comment by lucaswantz** [comment]
Vou implementar a parte de baixo do login...

**Comment by mbagatini** [comment]
Tela de login criada
